disabled_rules:
- trailing_whitespace
- identifier_name
#- private_over_fileprivate
- cyclomatic_complexity
- large_tuple
- weak_delegate
#- notification_center_detachment
#- block_based_kvo
#- for_where
#- multiple_closures_with_trailing_closure
- function_parameter_count
- type_body_length
- line_length
- type_name
- shorthand_operator
- statement_position
- nesting
- empty_enum_arguments
- redundant_optional_initialization
- unused_closure_parameter
- comment_spacing
- trailing_comma
- blanket_disable_command
- computed_accessors_order

opt_in_rules:
- empty_string
- unused_import
#- modifier_order
- weak_delegate
- force_unwrapping
- toggle_bool

function_body_length:
    warning: 300
    error: 500

#function_parameter_count:
#    warning: 6
#    error: 8

#type_body_length:
#    warning: 300
#    error: 700
    
#line_length:
#    warning: 250
#    error: 300
#    ignores_function_declarations: true
#    ignores_comments: true
#    ignores_urls: true
    
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
    
force_cast: warning
#force_try: warning
#identifier_name: warning
#large_tuple: warning
#empty_count: warning
#line_length: warning
weak_delegate: error

excluded: # paths to ignore during linting.
  - ./build
  - Build

reporter: "xcode"
